services:
  - type: web
    name: myntra-boards
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn myntra_web.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: myntra_web.settings
      - key: PYTHON_VERSION
        value: 3.11
